### ISSUE TITLE
Replace GTK2 dependency

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#1]
Using PyGObject:

> Python Bindings for GLib/GObject/GIO/GTK+
> PyGObject is a Python extension module that gives clean and consistent access to the entire 
> GNOME software platform through the use of GObject Introspection.

https://wiki.gnome.org/action/show/Projects/PyGObject

Debian package: python-gi

On 2017-02-15 11:43, EBo wrote:
> Looks like pythonOCC uses pygtk, which I've heard good things about
> but never used myself.  I have been using PyQt to develop a
> fairly sizable app for over a year now, and I would recommend
> it.  It is a python wrapping of the fairly massive Qt (C++)
> library and is very powerful but does have a significant learning
> curve.   Advantages:  cross-platform (Windows, Mac, Linux -- I
> develop on Linux), supported in conda/anaconda, which includes
> a pretty recent version (5.6.0 for python 2 -- I have to use
> python 2 for my app because of dependencies), and it can do
> just about anything you can imagine except giving your app the
> native Mac app menu bar at the top of the screen ... at least I
> haven't figured out how to make it do that yet! ;)

**Comment by njh** [comment]
I am a user of MusicBrainz Picard, which is written in Python and works well on Linux/Mac/Windows:
https://github.com/metabrainz/picard

It uses Qt4:
https://riverbankcomputing.com/software/pyqt/intro

And has support for a OpenQL widget:
http://pyqt.sourceforge.net/Docs/PyQt4/qglwidget.html

Looks well maintained...

**Comment by ebo** [comment]
Shouldn't this be marked as a feature request instead of an issue?

**Comment by laconc** [comment]
The current version is on GTK3; this issue has been addressed.

**Comment by sumpfralle** [comment]
Good reminder!
