### ISSUE TITLE
Engraving with Pocketing doesn't work (0.6.2)

### ISSUE THREAD

**Issue by jayMcBee** [SebKuzminsky/pycam#109]
Enabling Pocketing ('holes') in the Engraving strategy causes toolpath generation to fail with the error message on the Console that openvoronoi library failed to load.

**Comment by sumpfralle** [comment]
Indeed this is just an information (not an error). I clarified the wording now. Openvoronoi was not yet integrated, thus this warning does not really indicate a degraded behaviour.

What exactly is not working for you (besides the message)?

**Comment by jayMcBee** [comment]
Well - no toolpath is generated..

**Comment by sumpfralle** [comment]
Yes: sadly the pocketing algorithm of pycam is not stable - thus it fails for many (seemingly trivial) 2D shapes.

Maybe someone wants to work on the integration of an external pocketing library?

Possible candidates:
* opencamlib (#25)
* clipper (#26)

**Comment by sumpfralle** [comment]
See #114.
