### ISSUE TITLE
Crop toolpath: no selectable model

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#110]
![screenshot from 2018-01-13 13-36-02](https://user-images.githubusercontent.com/25838910/34906108-bf751ab8-f866-11e7-86bf-4f1d5aed11f9.png)

It is not possible to select a model, no model is visible.

**Comment by sumpfralle** [comment]
This dialog is a bit tricky, since it currently requires a 2D model. Thus it can be empty, if you only loaded 3D models at that moment.

I added a hint regarding this current restriction in 37fb8617733.
