### ISSUE TITLE
DXF import is ignoring holes

### ISSUE THREAD

**Issue by EvansMike** [SebKuzminsky/pycam#112]
PyCam-0.6.2 on Fedora Linux.

I have a simple dxf to import a rectangle and x4 3mm holes/circles. The holes are ignored. The error message is:

```
DXFImporter: Ignoring tiny ARC (between input line 1256 and 1274): (52.3, 257.7, 0.0) / 1.4 (0 - 360)
*** skipped 3 similar message(s) ***
DXFImporter: Imported DXF model (2D): 8 lines / 4 polygons
```
Pycam 0.5.1 imports holes just fine.

**Comment by sumpfralle** [comment]
Thanks for your report!
