### ISSUE TITLE
import SVG files directly

### ISSUE THREAD

**Issue by SebKuzminsky** [SebKuzminsky/pycam#119]
Currently PyCAM does not open SVG files directly.  SVG files are first converted to EPS by shelling out to inkscape, then the EPS is converted to DXF using pstoedit, then PyCAM reads the DXF file.  This is inefficient and error prone (for example #118).

It would be better to teach Importers.SVGImporter to parse SVG files and convert them directly to PyCAM's internal Geometry representation.

There are several python SVG libraries packaged for Debian Stretch we could investigate to see if they're appropriate for this:
* [python-cairosvg](https://packages.debian.org/stretch/python-cairosvg)
* [python-svg.path](https://packages.debian.org/stretch/python-svg.path)
* [python-rsvg](https://packages.debian.org/stretch/python-rsvg)
* [python-pyqt5.qtsvg](https://packages.debian.org/stretch/python-pyqt5.qtsvg)
* [python-uniconvertor](https://packages.debian.org/stretch/python-uniconvertor)

**Comment by sumpfralle** [comment]
Indeed, this would be a nice improvement!

One nice side-effect of the SVG->EPS->DXF conversion was the reduction to basic geometry objects (lines, circles, arcs). I do not know the SVG specification, but I could imagine, that it allows more (complicated) geometry primitives. (just wild guessing)
Anyway: the conversion really needs to go away.

**Comment by SebKuzminsky** [comment]
SVG does have additional, more complicated geometric primitives (quadratic and cubic bezier splines), but for now we can have it perform linear interpolation of all non-Line object, just like DXFImport does with arcs and circles.

**Comment by sumpfralle** [comment]
I am looking into "python3-svg.path" for now. It seems to be simple (interpreting only simple path types), but this should be suitable for us.
The `python3-svg.path` package is orphaned right now in Debian, but upstream looks active, thus I can imagine, that I will help maintaining that package.
Whichever option we pick: we will probably not be able to support all the complexity of the svg specification (e.g. transformations), but I guess, we can live with that.

**Comment by sumpfralle** [comment]
Implemented in f29c90a.
