### ISSUE TITLE
Slice removal doesnt work

### ISSUE THREAD

**Issue by mirecta** [SebKuzminsky/pycam#122]
i run fresh checkout with default object (cube) defauld bounds , and generate toolpath quick removal and path remove everything (cube too :D) if i choose slice removal type spiral , it is still grid

**Comment by sumpfralle** [comment]
Thank you for your report!

Are these two distinct issues, you are referring to? In this case: please open another issue.

In order to reproduce your issue, you need to share your model and your workspace settings file with us. Additionally you need to tell us the version of pycam you are using. Thanks!

**Comment by mirecta** [comment]
i dont touch anything i run program actual HEAD commit d0d0091014f518e6d193ac153028967a786fd3f9
and then i click Genetate toolpath
![pycam01](https://user-images.githubusercontent.com/1140680/43304631-26e1a49e-9175-11e8-979a-93cf9f29fd33.png)
![pycam02](https://user-images.githubusercontent.com/1140680/43304638-2d7c880a-9175-11e8-9796-fc1556daac68.png)
![pycam03](https://user-images.githubusercontent.com/1140680/43304641-31267f7e-9175-11e8-9e77-6504233af7cb.png)
![pycam04](https://user-images.githubusercontent.com/1140680/43304647-362e451a-9175-11e8-99e8-46b9a306dd76.png)
![pycam05](https://user-images.githubusercontent.com/1140680/43304653-38f0b6e8-9175-11e8-8c1e-6d5c0239f787.png)
![pycam06](https://user-images.githubusercontent.com/1140680/43304657-3b99b5f2-9175-11e8-8515-dc98c308f35f.png)

**Comment by mirecta** [comment]
as u can see on last image tool 6mm dia with this path remove everything

**Comment by sumpfralle** [comment]
Indeed the visualization was not correct - e.g. it lacked the tool path moves related to the safety height. Thus the visualization was misleading.
The export to a file was nevertheless correct.

Thank you for your report!
