### ISSUE TITLE
Slice removal patern spiral 

### ISSUE THREAD

**Issue by mirecta** [SebKuzminsky/pycam#123]
if i run pycam default project was set i only change in Processes pattern to Spiral and generate toolpath it seems nothing happend an path is still grid pattern

**Comment by sumpfralle** [comment]
Thank you for the report!

Indeed the path pattern was ignored before.

I fixed it partly. Now the setting itself is handled properly, but spiral-related settings currently have no effect (*rounded_corners* and *spiral direction*). This will follow ..
