### ISSUE TITLE
Support bridge fail

### ISSUE THREAD

**Issue by Pf441** [SebKuzminsky/pycam#125]
Good morning!
When I try to create the support model ("Models"->"Support"->"Create support model"), PyCAM console outputs an error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pycam-0.7.0_pre0.493.g0acbffb-py3.6.egg/pycam/Plugins/ModelSupport.py", line 137, in _add_support_model
    color=self.core.get("color_support_preview"))
TypeError: add_model() got an unexpected keyword argument 'name_template'
```
However, support preview is visible in the visualization.
![image](https://user-images.githubusercontent.com/35203464/44517796-e296be00-a6c8-11e8-9404-69a716442bca.png)

Is it a known bug or a problem with my configuration? I run Linux Mint 19 with the latest PyCAM commit.

**Comment by sumpfralle** [comment]
Thank you for your report - it is fixed now.
