### ISSUE TITLE
Critical gtk error on startup after clean install 

### ISSUE THREAD

**Issue by masterleo** [SebKuzminsky/pycam#126]

**Comment by masterleo** [comment]
I have this error 
![image](https://user-images.githubusercontent.com/8157302/45255523-e7759600-b387-11e8-9d2b-97ba38b17c42.png)

**Comment by masterleo** [comment]
all the dependencies seem to be installed. 
![image](https://user-images.githubusercontent.com/8157302/45255529-07a55500-b388-11e8-9733-fbf35e1f680c.png)

**Comment by sumpfralle** [comment]
This looks similar to #97.

Could you try [this recommendation](https://github.com/SebKuzminsky/pycam/issues/97#issuecomment-354177779) from that issue?

**Comment by sumpfralle** [comment]
I think, the issue is caused by #134.
