### ISSUE TITLE
webkit visualization: blank screen without MESA_GL_VERSION_OVERRIDE="3.0 Mesa 17.2.5"

### ISSUE THREAD

**Issue by sumpfralle** [SebKuzminsky/pycam#139]
See #138: the new webkit-based visualization (branch `replace-opengl-with-x3d`) shows a blank screen on a specific system. Setting the environment variable `MESA_GL_VERSION_OVERRIDE="3.0 Mesa 17.2.5"` works around this issue.

**Comment by valeriob01** [comment]
Right now it is working straight. No need for the MESA stuff. The buttons on top of the window (center, top, etc.) do not work.

![screenshot from 2019-02-15 11-15-37](https://user-images.githubusercontent.com/25838910/52850336-8363b480-3113-11e9-88fb-0c63cc2d52a6.png)

**Comment by sumpfralle** [comment]
I am glad to hear this and I hope, such issues will not haunt us anymore ...

Regarding the buttons: yes, indeed they are not working at the moment. This is the last blocker for the switch to this visualization, I think.
