### ISSUE TITLE
Guppy dependency

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#15]
The Memory Analyzer plugin requires the Guppy module which is not installed by default.

**Comment by njh** [comment]
Hm, there doesn't seem to be a Debian package for Guppy.

But there is for Ubuntu:
* http://packages.ubuntu.com/trusty/python-guppy

**Comment by sumpfralle** [comment]
The MemoryAnalyzer plugin is only useful for debugging and development.
Pycam handles the absence of guppy gracefully.
Do you think, that something needs to be done?

**Comment by SebKuzminsky** [comment]
python-guppy is currently Recommended by the pycam debian package, which means installing pycam will install guppy if it's available, but won't prevent installation of pycam if guppy is not available.  I think that's the best we can do for now.

If Debian adds python-guppy in the future we can promote it from Recommends to Depends.
