### ISSUE TITLE
Rescue old Wiki documentation

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#2]
For example:
http://sourceforge.net/apps/mediawiki/pycam/index.php?title=User_Manual

**Comment by SebKuzminsky** [comment]
I don't have a copy of the old wiki, but I fetched the 'pycam-media' repo from SF (https://sourceforge.net/p/pycam/media/)  and pushed it to this pycam repo as a branch called 'media'.

**Comment by njh** [comment]
I am putting the new website/documentation in a separate repo, for now.
We can merge the two, if it is a good idea in the future.

All the wiki pages as Markdown:
https://github.com/njh/pycam-website/

Test deployment here:
http://pycam.aelius.com/

**Comment by sumpfralle** [comment]
This is a great start!

**Comment by njh** [comment]
I am calling this complete. I have rescued and re-integrated the images and cleaned up some of the Markdown.

Any more work on this isn't about rescuing the old documentation.

I think work should continue in #21

**Comment by SebKuzminsky** [comment]
That's great!
