### ISSUE TITLE
Projecting engravings onto 3D models

### ISSUE THREAD

**Issue by sumpfralle** [SebKuzminsky/pycam#27]
t would be nice to be able to project a planar engraving (e.g. from a DXF file) onto a trimesh model (e.g. from an STL file). Combining the EngraveCutter (following lines) with a DropCutter (following heights) and moving each point of the resulting toolpath down the z axis should do the trick.

**Comment by thawkins** [comment]
would this allow me to cut profiles out from acrylic, i need to execute the same outline toolpath multiple times, but drop it down by a small amount on each pass, I can create stl files for my profiles in openscad, but i cant work out how to generate the required path in pycam. 

I have attached an example of what I want to do (example from grblSender) 


[electric_turtle.zip](https://github.com/SebKuzminsky/pycam/files/908941/electric_turtle.zip)

**Comment by sumpfralle** [comment]
This specific issue here discusses the projection of 2D models onto (non-flat) 3D models. I understand you are looking for a simple 2D toolpath instead.

Maybe these articles help you:
* [Input Formats](http://pycam.sourceforge.net/supported-formats/)
* [Processing 2D models](http://pycam.sourceforge.net/modeling-inkscape-svg/) (here: from inkscape)

**Comment by sumpfralle** [comment]
It works now:

![pycam-engrave-onto-3d-model](https://user-images.githubusercontent.com/1474141/44316414-bca0bd80-a42b-11e8-80e3-dae741694b29.png)
