### ISSUE TITLE
Replace psyco with PyPy

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#3]
pycam current has a dependency upon psyco.

> "Psyco is a historical project and only works on Python <= 2.6 on 32-bit x86 Intel CPUs."

https://pypi.python.org/pypi/psyco

> Psyco is unmaintained and dead. Please look at PyPy for the state-of-the-art in JIT compilers for Python.

http://psyco.sourceforge.net/

**Comment by njh** [comment]
At the moment running without psyco displays the following:
> Psyco is not available (performance will probably suffer slightly)

**Comment by sumpfralle** [comment]
I removed all references to `psyco` in order to get rid of the info message.

**Comment by sumpfralle** [comment]
If someone is interested in using pycam with the pypy intepreter, please open another issue.
