### ISSUE TITLE
Don't load the "Tiny pyramid" model if the user provides a Model on the command line

### ISSUE THREAD

**Issue by SebKuzminsky** [SebKuzminsky/pycam#30]
It's good to have a default Model pop up if the User doesn't request a specific one, but when the user *does* ask for a Model, "Tiny pyramid" just confuses things and clutters up the UI.

Also, the "PyCAM" name plate thingy is a more attractive default Model than the "Tiny pyramid".

**Comment by valeriob01** [comment]
similarly don't load the pycam-textbox model if a model is requested at command line.

**Comment by jtpedersen** [comment]
@valeriob01 From the looks of it that is the current behaviour?!

It did however always load the tiny triangle model

**Comment by sumpfralle** [comment]
fixed by @jtpedersen in  8f9f6d5dacf89cc09c5318dd5bc64a98e352e7cd
