### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by michahell** [SebKuzminsky/pycam#32]
> Extract the archive and run "python pycam"

```
pwd
/Users/michahell/Desktop/camshit/pycam

python pycam
/usr/local/opt/python/bin/python2.7: can't find '__main__' module in 'pycam'

python3 pycam
/usr/local/opt/python3/bin/python3.6: can't find '__main__' module in 'pycam'
```

how should this work, exactly? :(

**Comment by valeriob01** [comment]
cd pycam/scripts
./pycam

**Comment by sumpfralle** [comment]
@michahell: Is the problem solved for you?
Would you recommend a change of the documentation?

**Comment by jeromio** [comment]
Same happened to me. I'd suggest changing the docs to say 
`python scripts/pycam
`

**Comment by michahell** [comment]
yeap, what @jeromio said! i'll try again this weekend, somewhere, I hope, maybe 🐙
