### ISSUE TITLE
Install python-opengl with pycam

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#33]
It is required even in server mode.

**Comment by sumpfralle** [comment]
What do you mean? Is there doumentation of the dependency missing?
Where do you notice that the server mode indirectly requires python-opengl?

**Comment by valeriob01** [comment]
On Sun, 2017-02-26 at 06:42 -0800, sumpfralle wrote:
> What do you mean? Is there doumentation of the dependency missing?
> Where do you notice that the server mode indirectly requires python-opengl?


I have installed pycam on a fresh installation of Debian 8.2, when
starting with --start-server-only it complained about opengl.

**Comment by sumpfralle** [comment]
OK - I think, this one is it.
