### ISSUE TITLE
Toolpath just carves the bounding box

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#43]
From: https://sourceforge.net/p/pycam/discussion/860183/thread/7919edfd/

**Oleg Kirillov - 2 hours ago**
> Hi!
> Installed on Ubuntu 16.04, tried to make a gcode for pycam.stl. Unfortunately the toolpath
> seemed to cut out everything inside the bounds. I decided to test and confirmed - tool makes just > a flat-bottomed box, nothing more. Other STLs produce the same.
> Where should I start to investigate?

**Oleg Kirillov - 32 minutes ago**
> PS. Found both the cause and the solution.
> https://sourceforge.net/p/pycam/patches/15/
> Maybe this should be fixed.

The patch says:

**Creator: J. Cugnoni, 2013-11-27**

> Under Ubuntu 12.04 and 13.04, in the Tasks GUI, the Collision Models table is not visible.
> To fix this issue, I have modified pycam/Plugins/TasksParameters.py line 37:
>
> ```self.control.get_widget().set_size_request(240, -1)```
>
> to
>
> ```self.control.get_widget().set_size_request(240, 120)```
>
> I am not 100% sure that 120 is the best value, but it works well for me at least.
> Please, fix this a future release and thanks a lot for this great code !

**Comment by sumpfralle** [comment]
Thank you for moving this issue here!
