### ISSUE TITLE
Distributed processing disabled unless some action taken

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#48]
![screenshot - 03212017 - 01 56 45 pm](https://cloud.githubusercontent.com/assets/25838910/24146404/dba4808c-0e35-11e7-9e38-b92c9882ee52.png)

To enable distributed processing it is necessary to deselect and reselect the "Enable parallel processes" check-box.

**Comment by sumpfralle** [comment]
You discover all the small details :)
