### ISSUE TITLE
Error while creating a new Process

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#52]
To reproduce
-----------------
- connect to a task server (running under pypy)
- try to create a new Process by clicking the New button

![screenshot - 04182017 - 01 13 27 pm](https://cloud.githubusercontent.com/assets/25838910/25125895/b8c65e94-2430-11e7-8fd8-e08ace92c180.png)

**Comment by sumpfralle** [comment]
The top of the screenshot indicates that some plugins were not loaded. This is probably the reason for the missing "strategies", that cause the error.

Probably you should take a look at the first failing plugin and investigate, why it fails.

btw: I never heard of anyone using pypy with pycam. Thus you are entering new territory - have fun!

**Comment by valeriob01** [comment]
On Tue, 2017-04-18 at 13:36 -0700, sumpfralle wrote:
> The top of the screenshot indicates that some plugins were not loaded. This is probably the reason for the missing "strategies", that cause the error.
> 
> Probably you should take a look at the first failing plugin and investigate, why it fails.


I have re-cloned pycam and started it normally, The first plugin to fail
is PathParameters.py, so probably you should also investigate.


> btw: I never heard of anyone using pypy with pycam. Thus you are entering new territory - have fun!


- The task server running under pypy, that was only a start at
experimentation.

**Comment by valeriob01** [comment]
There are 3 plugins that fail, you should probably investigate also:
PathParameters, PathPatterns, and ProcessStrategies.
![screenshot - 04192017 - 09 32 31 am](https://cloud.githubusercontent.com/assets/25838910/25166349/42f9fe22-24db-11e7-9e9f-6d61e491db06.png)

**Comment by valeriob01** [comment]
Probably the last changes to the plugins in question "Switch POCKETING_TYPE_* to enum 'PocketingType'" is the problem...

**Comment by valeriob01** [comment]
On Tue, 2017-04-18 at 13:36 -0700, sumpfralle wrote:
> The top of the screenshot indicates that some plugins were not loaded. This is probably the reason for the missing "strategies", that cause the error.
> 
> Probably you should take a look at the first failing plugin and investigate, why it fails.
> 
> btw: I never heard of anyone using pypy with pycam. Thus you are entering new territory - have fun!
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SebKuzminsky/pycam/issues/52#issuecomment-294973681


3 plugins are failing: PathParameters, PathPatterns and
ProcessStrategies,

The reason of the fail (I think): 

https://github.com/SebKuzminsky/pycam/commit/8a9bf8bf58fb748f51081aef8b8214b5bd637636

**Comment by sumpfralle** [comment]
The above commit implies a new dependency on `enum34`. Did you install it?
I guess, this problem could be hidden by the plugin loader.

**Comment by valeriob01** [comment]
No I didn't install it because nowhere a message about that.

**Comment by valeriob01** [comment]
On Wed, 2017-04-19 at 11:07 -0700, sumpfralle wrote:
> The above commit implies a new dependency on `enum34`. Did you install it?
> I guess, this problem could be hidden by the plugin loader.

My attempt to install enum34 in Linuxcnc has failed, I switched to
another machine with Debian to see if I could install the python-enum34
package, obviously also wanted python-gtkglext1 and python-opengl.

I am going to close the issue.
