### ISSUE TITLE
save tools, processes and bounds - howto

### ISSUE THREAD

**Issue by cki61** [SebKuzminsky/pycam#53]
I'm using PyCAM 0.6.1 with openSUSE 42.2. All tools, processes and bounds created are gone after a restart. How can I save the mentioned configs? Didn't find a 'save' possibility. Sorry.
Reg. cki61

**Comment by sumpfralle** [comment]
This feature was working with v0.5.x, but got lost due to various internal changes in v0.6.0.
I am not aware of someone working on its revival.

**Comment by sumpfralle** [comment]
This feature is now part of the current master branch ("save workspace").
