### ISSUE TITLE
Convert text files to Markdown

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#6]
This will make them more readable on the web

**Comment by SebKuzminsky** [comment]
I saw you updated the README, it looks great now.  I removed the old README.TXT file to avoid confusion.  I think that's all we need to convert to Markdown, or do you have any other files in mind?

**Comment by njh** [comment]
I didn't delete README.txt because the build depended on it - thanks for fixing that.

I was planning to convert all the files in root currently ending .txt....

**Comment by sumpfralle** [comment]
@njh: you already migrated everything, or?
