### ISSUE TITLE
Specify multiple servers when distributed processing mode is enabled

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#60]
This enhancement could bring the possibility to specify a list of servers, and each server is used in parallel with other servers to increase the number of available cores.

**Comment by sumpfralle** [comment]
Personally I am not in favor of putting more effort into the distributed processing. It is is a nice feature, but it is also probably the third most often mentioned cause of problem reports (besides the OpenGL visualization and toolpath algorithms). Thus I am not confident, that the effort put into this feature is justified.
Anyway: patches and pull requests are welcome!

**Comment by valeriob01** [comment]
This could introduce more bugs than features. It works well now as it is. With the number of cores available at good price it is not an issue anymore.
