### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by laconc** [SebKuzminsky/pycam#61]
I made a quick docker image to get pycam on my mac. Is there any interest in the idea of me polishing it and creating a PR?

![screen shot 2017-06-21 at 10 45 41 pm](https://user-images.githubusercontent.com/20423536/27416606-1969c850-56d4-11e7-8a89-60807d0ac342.png)

**Comment by matelakat** [comment]
@laconc yes please, I am interested in this.

**Comment by ebo** [comment]
Oh YEA...  This will allow people to set up an alternative install 
method, so that if they have issues with a regular source install, they 
can get something "just working".  Also, it would allow for 
configuration and compatibility testing (think test driven development, 
etc.).  Good stuff.

**Comment by laconc** [comment]
Sweet, I'll get on it. I'm in the middle of finishing up some summer classes so I probably won't have something until next week.

**Comment by matelakat** [comment]
@laconc could you just open a PR with what you have, mark it as WIP ?

**Comment by laconc** [comment]
@matelakat done.

#62

**Comment by laconc** [comment]
The PR has had quite a bit of development work done to it, closing this.
