### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by valeriob01** [SebKuzminsky/pycam#64]
When creating a new process:

![screenshot from 2017-06-30 11-09-22](https://user-images.githubusercontent.com/25838910/27729016-71b44006-5d84-11e7-9930-a7091d39c40d.png)

**Comment by sumpfralle** [comment]
Does this happen every time you start pycam? If yes: please show us the complete log.

Currently I cannot reproduce this.

**Comment by valeriob01** [comment]
On Sat, 2017-11-11 at 03:59 +0000, sumpfralle wrote:
> Does this happen every time you start pycam? If yes: please show us the complete log.
> 
> Currently I cannot reproduce this.


This bug was related to an old version of pycam.

No surprise you cannot reproduce it now.

**Comment by valeriob01** [comment]
On Sat, 2017-11-11 at 03:59 +0000, sumpfralle wrote:
> Does this happen every time you start pycam? If yes: please show us the complete log.
> 
> Currently I cannot reproduce this.


BTW, the screenshot shows the portion of visible output, and the trace
shows that various actions where made before triggering the bug

It does not show when you load pycam, it shows after various actions of
the user

**Comment by sumpfralle** [comment]
> This bug was related to an old version of pycam.

In this case I suggest to leave it rest in peace :)
