### ISSUE TITLE
Decide on what to do about gtkglext visualisation

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#7]
> The problematic part of this is the usage of the gtkglext module for the 3D
> visualization. We would need to replace it or at least throw it away (and add
> another visualization later). The gtkglext module is only working with Python 2
> and there were no binary releases (especially for Windows) for quite some time.

**Comment by sumpfralle** [comment]
We switched to gtk.GLArea (available since GTK v3.16).
