### ISSUE TITLE
Update Debian packaging

### ISSUE THREAD

**Issue by njh** [SebKuzminsky/pycam#8]
On 2017-02-15 17:31, Sebastian Kuzminsky wrote:
> I will work on updating the packaging to build on Debian Jessie and 
> Stretch.  As soon as we have something that installs and runs on 
> whatever platforms we have volunteer platform maintainers for I suggest 
> we make a 0.6 release, to get the software into the hands of ourselves 
> and other users ASAP.

**Comment by SebKuzminsky** [comment]
Done.  Released 0.6.
