### ISSUE TITLE
The Engrave/Trace Model field is displayed too small

### ISSUE THREAD

**Issue by zancas** [SebKuzminsky/pycam#81]
<img width="1037" alt="modelunavailable" src="https://user-images.githubusercontent.com/640955/31858377-64a3b526-b6b3-11e7-9598-e8c4fb67a7a2.png">

The commit I was running against when I generated the above screenshot:

```
commit a815accdc116f032b943b803b1e1e709604686c2 (origin/master, origin/HEAD, master)
Merge: 6269405 e4cb8d4
Author: Sebastian Kuzminsky <seb@highlab.com>
Date:   Mon Oct 16 19:39:44 2017 -0600

    Merge remote-tracking branch 'origin/stable/0.6'
```

**Comment by zancas** [comment]
This was originally mentioned in issue:  #79 .   Now that it's tracked here I am editing that issue to remove the redundant data.

**Comment by sumpfralle** [comment]
Thank you for the report!

I could not find a good way to adjust the size of the ScrolledWindow element to its children. Thus I defined a fixed width. If anyone knows a better approach, then I would like to improve that.

The issue is fixed in master. It does not apply to stable/0.6.
